### ISSUE TITLE
Lua Error

### ISSUE THREAD

**Issue by Jaidy88** [muhmiauwau/AuctionHouseCustomCategories#1]
I just get a Lua Error an see nothing:

1x AuctionHouseCustomCategories/sort.lua:14: attempt to compare string with nil
[string "@AuctionHouseCustomCategories/sort.lua"]:14: in function <AuctionHouseCustomCategories/sort.lua:14>
[string "=[C]"]: in function `sort'
[string "@AuctionHouseCustomCategories/sort.lua"]:65: in function `sortResult'
[string "@AuctionHouseCustomCategories/AHCC.lua"]:72: in function <AuctionHouseCustomCategories/AHCC.lua:49>

Locals:
k1 = <table> {
 itemKey = <table> {
 }
 stat2 = 0
 name = "Gyroskopisches Kaleidoskop"
 stat1 = 11
 containsOwnerItem = false
 minPrice = 1
 totalQuantity = 1
 quality = 3
}
k2 = <table> {
 itemKey = <table> {
 }
 stat2 = 0
 totalQuantity = 1
 stat1 = 1
 minPrice = 1
 containsOwnerItem = false
 quality = 3
}
(*temporary) = "Gyroskopisches Kaleidoskop"
(*temporary) = nil
(*temporary) = "attempt to compare string with nil"
key = "name"

**Comment by Jaidy88** [comment]
2x AuctionHouseCustomCategories/sort.lua:14: attempt to compare two nil values
[string "@AuctionHouseCustomCategories/sort.lua"]:14: in function <AuctionHouseCustomCategories/sort.lua:14>
[string "=[C]"]: in function `sort'
[string "@AuctionHouseCustomCategories/sort.lua"]:65: in function `sortResult'
[string "@AuctionHouseCustomCategories/AHCC.lua"]:72: in function <AuctionHouseCustomCategories/AHCC.lua:49>

Locals:
k1 = <table> {
 itemKey = <table> {
 }
 stat2 = 0
 totalQuantity = 1
 stat1 = 7
 minPrice = 1
 containsOwnerItem = false
 quality = 3
}
k2 = <table> {
 itemKey = <table> {
 }
 stat2 = 0
 totalQuantity = 1
 stat1 = 7
 minPrice = 1
 containsOwnerItem = false
 quality = 3
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to compare two nil values"
key = "name"

**Comment by muhmiauwau** [comment]
Hi @Jaidy88, thank you for reporting that issue.
Took me a bit to find the problem, but i think i fixed that now.

**Comment by Jaidy88** [comment]
Amazing :) works
